[package]
name = "push_notifications_types"
version = "0.1.0"
edition = "2021"

[dependencies]
hdi = { workspace = true }
holochain_serialized_bytes = { workspace = true }
serde = { workspace = true }
