[package]
name = "push_notifications_service"
version = "0.0.1"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]
name = "push_notifications_service"

[dependencies]
hdi = { workspace = true }

serde = { workspace = true }
